### ISSUE TITLE
2023/04/12 14:03:32 chatgpt.go:142: Post "https://api.openai.com/v1/chat/completions": unexpected EOF

### ISSUE THREAD

**Issue by Nihilism0** [SuInk/QQ-ChatGPT-Bot#10]
how to solve it

**Comment by SuInk** [comment]
if u are in china mainland,  pls use proxy.

**Comment by Nihilism0** [comment]
> if u are in china mainland, pls use proxy.

I have already set up the system agent, and the same result is still achieved. Sometimes, it can be successful once or twice, but most of the time, this error is reported

**Comment by SuInk** [comment]
i guess this due to openai: 
https://www.v2ex.com/t/930657

**Comment by Nihilism0** [comment]
> i guess this due to openai: https://www.v2ex.com/t/930657

OK，I will try it
