### ISSUE TITLE
功能意见：将openai的域名放在配置中

### ISSUE THREAD

**Issue by lxgz12345** [SuInk/QQ-ChatGPT-Bot#12]
功能意见：将openai的域名放在配置中，方便使用镜像站

**Comment by lvyonghuan** [comment]
cqhttp还可以用吗，不是说腾讯在封杀那块的机器人了
另外这个项目本身也有点结构性bug，我之前pr的时候还太年轻没啥经验，自己弄了这个bug
如果cqhttp不能用的话再用这个项目感觉意义不大了，还能用的话倒是还可以再改改代码

**Comment by lxgz12345** [comment]
能登陆，但是我试了很多机器人项目，各个项目的机器人总是有些问题，要么登不上（m开头的那个登陆框架，没有扫码登不上），要么登上了（cqhttp）但没有合适的机器人项目，还有一个都配置好了告诉我API调用失败。

登录只能用手表协议加扫码登录，其他的都报错。

我想的是用下面图片里的这种配置项，只需要OPENAI密钥、API域名、对话模型以及模型参数，并且由于使用了第三方转发API的服务，所以不需要开代理，第三方转发服务来自WildCard。

如果大佬能重新开始维护此仓库，我也很高兴能继续搭建使用。

![QQ截图20240505165922](https://github.com/SuInk/QQ-ChatGPT-Bot/assets/51988982/f8c5e4f1-d49c-4d52-8bd3-a2862d16108b)

**Comment by lvyonghuan** [comment]
> 能登陆，但是我试了很多机器人项目，各个项目的机器人总是有些问题，要么登不上（m开头的那个登陆框架），要么登上了（cqhttp）但没有合适的机器人项目，还有一个都配置好了告诉我API调用失败。 登录只能用手表协议加扫码登录，其他的都报错。 我想的是用下面图片里的这种配置项，只需要OPENAI密钥、API域名、对话模型以及模型参数，并且由于使用了第三方转发API的服务，所以不需要开代理，第三方转发服务来自WildCard。

我大概知道你的意思，我在这之后又干过几个月类似的活
要有时间的话我可以修理下。不过感觉鉴于cqhttp已经不稳定了，可能还是等新东西出来比较好。（不过老实说我感觉按腾讯的势头，可能也难说有没有新东西
我要有空的话看看吧，主要是我现在没API可以用来测试了，只剩azure的

---
~~其实主要是pr的代码是我新手期写的，我不是很能忍住去看那一坨~~

**Comment by lxgz12345** [comment]
> > 能登陆，但是我试了很多机器人项目，各个项目的机器人总是有些问题，要么登不上（m开头的那个登陆框架），要么登上了（cqhttp）但没有合适的机器人项目，还有一个都配置好了告诉我API调用失败。 登录只能用手表协议加扫码登录，其他的都报错。 我想的是用下面图片里的这种配置项，只需要OPENAI密钥、API域名、对话模型以及模型参数，并且由于使用了第三方转发API的服务，所以不需要开代理，第三方转发服务来自WildCard。
> 
> 我大概知道你的意思，我在这之后又干过几个月类似的活 要有时间的话我可以修理下。不过感觉鉴于cqhttp已经不稳定了，可能还是等新东西出来比较好。（不过老实说我感觉按腾讯的势头，可能也难说有没有新东西 我要有空的话看看吧，主要是我现在没API可以用来测试了，只剩azure的
> 
> ~其实主要是pr的代码是我新手期写的，我不是很能忍住去看那一坨~

我可以提供API，同样的地址不同的密钥，仅仅测试几下我还是可以支持的，虽然也是付费的，但花费少的话我也不收你费用，我估计5$左右吧，大哥可以加一下我的QQ***聊天

**Comment by lvyonghuan** [comment]
> > > 能登陆，但是我试了很多机器人项目，各个项目的机器人总是有些问题，要么登不上（m开头的那个登陆框架），要么登上了（cqhttp）但没有合适的机器人项目，还有一个都配置好了告诉我API调用失败。 登录只能用手表协议加扫码登录，其他的都报错。 我想的是用下面图片里的这种配置项，只需要OPENAI密钥、API域名、对话模型以及模型参数，并且由于使用了第三方转发API的服务，所以不需要开代理，第三方转发服务来自WildCard。
> > 
> > 
> > 我大概知道你的意思，我在这之后又干过几个月类似的活 要有时间的话我可以修理下。不过感觉鉴于cqhttp已经不稳定了，可能还是等新东西出来比较好。（不过老实说我感觉按腾讯的势头，可能也难说有没有新东西 我要有空的话看看吧，主要是我现在没API可以用来测试了，只剩azure的
> > ~其实主要是pr的代码是我新手期写的，我不是很能忍住去看那一坨~
> 
> 我可以提供API，同样的地址不同的密钥，仅仅测试几下我还是可以支持的，虽然也是付费的，但花费少的话我也不收你费用，我估计5$左右吧，大哥可以加一下我的QQ2370177068聊天

有API文档之类的吗，我得先确认一下request的格式

**Comment by lxgz12345** [comment]
> > > > 能登陆，但是我试了很多机器人项目，各个项目的机器人总是有些问题，要么登不上（m开头的那个登陆框架），要么登上了（cqhttp）但没有合适的机器人项目，还有一个都配置好了告诉我API调用失败。 登录只能用手表协议加扫码登录，其他的都报错。 我想的是用下面图片里的这种配置项，只需要OPENAI密钥、API域名、对话模型以及模型参数，并且由于使用了第三方转发API的服务，所以不需要开代理，第三方转发服务来自WildCard。
> > > 
> > > 
> > > 我大概知道你的意思，我在这之后又干过几个月类似的活 要有时间的话我可以修理下。不过感觉鉴于cqhttp已经不稳定了，可能还是等新东西出来比较好。（不过老实说我感觉按腾讯的势头，可能也难说有没有新东西 我要有空的话看看吧，主要是我现在没API可以用来测试了，只剩azure的
> > > ~其实主要是pr的代码是我新手期写的，我不是很能忍住去看那一坨~
> > 
> > 
> > 我可以提供API，同样的地址不同的密钥，仅仅测试几下我还是可以支持的，虽然也是付费的，但花费少的话我也不收你费用，我估计5$左右吧，大哥可以加一下我的QQ***聊天
> 
> 有API文档之类的吗，我得先确认一下request的格式

WildCard那边没有文档，应该与OpenAI官方是一样

**Comment by SuInk** [comment]
把大佬设为项目成员了 @lvyonghuan

**Comment by lvyonghuan** [comment]
https://github.com/lvyonghuan/QQ-ChatGPT-Bot
@lxgz12345 我先推到我的fork上了。有小半年没碰过openai的API了，还是有些小问题。角色扮演有些变动，目前可能没用（不过如果要使用的话，参考我在config里写的，role和下面的message数组构成一系列一一顺序映射的键值对）我只用azure的api测试过，能正常跑。还没用QQ bot测试，你可以先看看。镜像站的API可能有些不一样，如果有报错可以回我。不过最近DDL有点多，不一定能很快处理。
https://github.com/lvyonghuan/QQ-ChatGPT-Bot/releases/tag/1.0

**Comment by lxgz12345** [comment]
@lvyonghuan 
太好了哥们，能用了！不过有个问题，配置文件的扩展名到底是cfg还是toml，自动生成的是cfg，读取的是toml？？
还有一个小问题，机器人除了正常聊天，有其他的命令吗？
![f7821cf7c469ddab56b842912f0a83a8](https://github.com/SuInk/QQ-ChatGPT-Bot/assets/51988982/faaf8c8d-c4f0-4a8c-b98f-0b7d3931bda5)

**Comment by SuInk** [comment]
> @lvyonghuan 太好了哥们，能用了！不过有个问题，配置文件的扩展名到底是cfg还是toml，自动生成的是cfg，读取的是toml？？ 还有一个小问题，机器人除了正常聊天，有其他的命令吗？ ![f7821cf7c469ddab56b842912f0a83a8](https://private-user-images.githubusercontent.com/51988982/329818655-faaf8c8d-c4f0-4a8c-b98f-0b7d3931bda5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NzQ0MzMsIm5iZiI6MTcxNTQ3NDEzMywicGF0aCI6Ii81MTk4ODk4Mi8zMjk4MTg2NTUtZmFhZjhjOGQtYzRmMC00YThjLWI5OGYtMGI3ZDM5MzFiZGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDAwMzUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzODlkYTE5NTA0YTMxYzYxMjk0Y2IyODk2NTJhNWQ5NWE3ZTZjYWQzYTYyMTMzY2I5YzIwYzdkYzFiNzBhMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.79OsvQo9V2g5MmXpzoBj_zdJIn-XXYGjllLSXbz8U1M)

文件后缀是cfg，格式是toml，相当于把toml改了后缀为cfg生成文件和读取的，应该是这样

**Comment by lvyonghuan** [comment]
> @lvyonghuan 太好了哥们，能用了！不过有个问题，配置文件的扩展名到底是cfg还是toml，自动生成的是cfg，读取的是toml？？ 还有一个小问题，机器人除了正常聊天，有其他的命令吗？ ![f7821cf7c469ddab56b842912f0a83a8](https://private-user-images.githubusercontent.com/51988982/329818655-faaf8c8d-c4f0-4a8c-b98f-0b7d3931bda5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NzY2MjQsIm5iZiI6MTcxNTQ3NjMyNCwicGF0aCI6Ii81MTk4ODk4Mi8zMjk4MTg2NTUtZmFhZjhjOGQtYzRmMC00YThjLWI5OGYtMGI3ZDM5MzFiZGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDAxMTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNjA1Yjg5YjIxN2M4MGE5ZDc4NGUyZThmNzBhMDhhNDc4ZWIzYjQxMDczMDkxYTRjOWY2Yzk2MDJmODhjNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Xta9kh_WN-qwVOMNkhU5npAmS6zh-Wf8FDGnQQtPMk)

后缀确实是toml。
目前应该只有聊天，其他功能要做应该也行，但是鉴于cqhttp目前的情况，API有多少被围堵了我也不清楚。而且这项目代码也有点久了。另外这段时间在弄工作室项目，时间也不算很多。
基于NTQQ协议的库好像已经有了，先观望下。
另外openai api的参数其实还有一坨，我半年没读了，一时半会也弄不清楚（
