### ISSUE TITLE
有时输出的文本不会换行

### ISSUE THREAD

**Issue by Admmmmmmin** [SuInk/QQ-ChatGPT-Bot#3]
输出的文本有时不会换行，黏在一块十分难读，请问有可能的原因和解决方案吗？

**Comment by SuInk** [comment]
有图吗

**Comment by Admmmmmmin** [comment]
> 有图吗

第一张是 go-cqhtp 搭配 QQ-ChatGPT-Bot 生成的文本，图二是其他基于 mcl 的 ChatBot 生成的文本。


![图一](https://user-images.githubusercontent.com/78294316/224223740-ae6e3361-d83d-414f-ae4a-b0b58ccfeb44.jpg)

![图二](https://user-images.githubusercontent.com/78294316/224224029-a8e3a7d9-9003-41c5-abb1-e413850f5e53.jpg)

**Comment by SuInk** [comment]
> > 有图吗
> 
> 第一张是 go-cqhtp 搭配 QQ-ChatGPT-Bot 生成的文本，图二是其他基于 mcl 的 ChatBot 生成的文本。
> 
> ![图一](https://user-images.githubusercontent.com/78294316/224223740-ae6e3361-d83d-414f-ae4a-b0b58ccfeb44.jpg)
> 
> ![图二](https://user-images.githubusercontent.com/78294316/224224029-a8e3a7d9-9003-41c5-abb1-e413850f5e53.jpg)

已更新
