### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by Doraemonsan** [SuInk/QQ-ChatGPT-Bot#5]
可不可以新增除了at以外的触发方式，如关键字触发，想要私聊使用

**Comment by SuInk** [comment]
私聊是直接就回答的，不用@~

**Comment by Doraemonsan** [comment]
好的谢谢，刚刚应该是网络不太行半天没回复我还以为没有私聊，但是还是想麻烦加入关键字触发，目前号上挂了有其他插件，直接触发有功能冲突

**Comment by SuInk** [comment]
> 好的谢谢，刚刚应该是网络不太行半天没回复我还以为没有私聊，但是还是想麻烦加入关键字触发，目前号上挂了有其他插件，直接触发有功能冲突

感谢😊

**Comment by Doraemonsan** [comment]
在使用中发现一个问题，当发出去的信息里包含换行时插件不能正确处理，会报：
2023/03/24 23:38:42 chatgpt.go:82: OpenAI API调用失败，返回内容： {
    "error": {
        "message": "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please send an email to support@openai.com and include any relevant code you'd like help with.)",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

**Comment by SuInk** [comment]
> 

感谢反馈

**Comment by SuInk** [comment]
已支持关键词触发,请下载新版并参照config.cfg.example修改config.cfg文件
